# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#default

gui:
  # If true, do not show a warning when discarding changes in the staging view.
  skipDiscardChangeWarning: true

  # If true, display the files in the file views as a tree. If false, display the files as a flat list.
  # This can be toggled from within Lazygit with the '`' key, but that will not change the default.
  showFileTree: true

  # If true, hunk selection mode will be enabled by default when entering the staging view.
  useHunkModeInStagingView: false

git:
  # If true, git diffs are rendered with the `--ignore-all-space` flag, which
  # ignores whitespace changes. Can be toggled from within Lazygit with `<c-w>`.
  ignoreWhitespaceInDiffView: true

  # The number of lines of context to show around each diff hunk. Can be changed
  # from within Lazygit with the `{` and `}` keys.
  diffContextSize: 10

  # If not "none", lazygit will automatically fast-forward local branches to match
  # their upstream after fetching. Applies to branches that are not the currently
  # checked out branch, and only to those that are strictly behind their upstream
  # (as opposed to diverged).
  # Possible values: 'none' | 'onlyMainBranches' | 'allBranches'
  autoForwardBranches: "none"
